dist: xenial
sudo: required
language: python
python:
-   "3.5"
install:
-   sudo add-apt-repository -y ppa:deadsnakes/ppa
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.9 python3.9-dev weka libsvm-java libsvm3-java
script:
-   ./init_virtualenv.sh
-   ./pep8.sh
-   tox
