dist: xenial
sudo: required
language: python
python:
-   "3.5"
install:
-   sudo add-apt-repository -y ppa:deadsnakes/ppa
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.6 python3.6-dev weka libsvm-java libsvm3-java
-   pip install -r requirements-test.txt
script:
-   ./pep8.sh
-   tox
