name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # This should match what's used in init_virtualenv.sh.
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y weka libsvm-java libsvm3-java
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt

#    - name: Run init_virtualenv.sh
#      run: ./init_virtualenv.sh

    - name: Run PEP8 check
      run: ./pep8.sh

    - name: Run tests with tox
      run: ./test.sh
